apiVersion: v1
kind: Secret
metadata:
  name: portal-db-secret
  namespace: portal
type: Opaque
stringData:
  DB_HOST: "portal-postgres"
  DB_PORT: "5432"
  DB_NAME: "hrdb"
  DB_USER: "innovatech_admin"
  DB_PASSWORD: "SuperSecret123!"
