apiVersion: v1
kind: Secret
metadata:
  name: portal-db
  namespace: portal
type: Opaque
stringData:
  DB_HOST: "innovatech-hrdb-dev.cxigqeymkpkb.eu-west-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "hrdb"
  DB_USER: "innovatech_admin"
  DB_PASSWORD: "VerySecure123!"
