apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-frontend
  namespace: portal
  labels:
    app: portal-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-frontend
  template:
    metadata:
      labels:
        app: portal-frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: portal-frontend-files
              mountPath: /usr/share/nginx/html
            - name: portal-nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: portal-frontend-files
          configMap:
            name: portal-frontend-config
            items:
              - key: index.html
                path: index.html
              - key: styles.css
                path: styles.css
              - key: script.js
                path: script.js
        - name: portal-nginx-conf
          configMap:
            name: portal-frontend-config
            items:
              - key: nginx.conf
                path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: portal-frontend-svc
  namespace: portal
  labels:
    app: portal-frontend
spec:
  type: LoadBalancer
  selector:
    app: portal-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
