apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-hr-api
  namespace: portal
  labels:
    app: portal-hr-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-hr-api
  template:
    metadata:
      labels:
        app: portal-hr-api
    spec:
      containers:
        - name: hr-api
          image: omarwadeh/portal-hr-api:v2        # <- zorg dat je deze tag hebt gepusht
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: portal-db-secret
          env:
            - name: NODE_ENV
              value: "production"
            - name: AWS_REGION
              value: "eu-west-1"                  # jouw regio
            - name: LAMBDA_ONBOARD_URL
              value: "https://2xodlglkez4w3p6fwlj7idhc7q0wkjoc.lambda-url.eu-west-1.on.aws/"                 # naam van je Lambda
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: portal-hr-api-svc
  namespace: portal
  labels:
    app: portal-hr-api
spec:
  selector:
    app: portal-hr-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
