apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-nginx-conf
  namespace: portal
data:
  nginx.conf: |
    events {}
    http {
      upstream hr_api {
        server portal-hr-api-svc.portal.svc.cluster.local:80;
      }
      server {
        listen 80;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
        location /api/ {
          proxy_pass http://hr_api/;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-nginx
  namespace: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-nginx
  template:
    metadata:
      labels:
        app: portal-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: portal-frontend
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: nginx-conf
          configMap:
            name: portal-nginx-conf
        - name: portal-frontend
          configMap:
            name: portal-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: portal-nginx-svc
  namespace: portal
spec:
  type: LoadBalancer
  selector:
    app: portal-nginx
  ports:
    - port: 80
      targetPort: 80
